### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by dschick** [MBI-Div-B/pytango-PIHexapod#2]
I would like to suggest a few improvements for the hexapod here:

1. the axis position should get a unit (mm, deg)
2. the limits should be handled via the state of the axis (Alarm)
3. would be nice to invert the direction of individual axis. either by a boolean or a more general DESY-like conversion-factor.

What do you think?

**Comment by dscran** [comment]
The way we're currently handling limits is not reliable: we query axis limits and compare the current axis position against these limits. The issue is, that these are theoretical values that are only accurate for the default pivot point and when _all other axes_ are at zero position.

The manual recommends to check whether a target position is reachable before sending the movement command. I implemented this in the linked branch. Unit assignment and inverted flag are also implemented there.

I tested it briefly on our hexapod, please also check it works for yours.
